repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
    stages:
    - commit
  - id: end-of-file-fixer
    stages:
    - commit
  - id: trailing-whitespace
    stages:
    - commit
- repo: local
  hooks:
  - id: make-typed
    name: make typed
    entry: daves-dev-tools make-typed
    language: system
    pass_filenames: false
    always_run: true
    stages:
    - commit
  - id: make-requirements
    name: make requirements
    entry: make requirements
    language: system
    pass_filenames: false
    always_run: true
    stages:
    - commit
  - id: black
    name: black
    entry: black
    language: system
    types_or:
    - python
    - pyi
    stages:
    - commit
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types_or:
    - python
    - pyi
    stages:
    - commit
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types_or:
    - python
    - pyi
    stages:
    - commit
  - id: git-tag-version
    name: daves-dev-tools git tag-version
    entry: daves-dev-tools git tag-version
    language: system
    pass_filenames: false
    always_run: true
    stages:
    - push
    require_serial: true
  - id: git-push-tags
    name: git push --no-verify --tags
    entry: git push --no-verify --tags
    language: system
    pass_filenames: false
    always_run: true
    stages:
    - push
    require_serial: true
