name: distribute
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - pyproject.toml
    - setup.py
    - setup.cfg
jobs:
  distribute:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install
      run: make ci-install
    - name: tag version
      run: venv/bin/daves-dev-tools git tag-version
    - name: push tags
      run: git push --tags
    - name: create release
      run: gh release create "$(venv/bin/python setup.py --version)" || echo "Release already exists"
    - name: distribute
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: make distribute
